### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by Alerno** [Makpptfox/New-World-Refining-Calculator#1]
Hi, it would be great to be able to resize the window smaller. I have two monitors and second one is vertical (size of table) and when I moved the window there I was not able to resize it smaller. But if I toggle fullscreen it does resize it to correct width, but I'm unable to use anything else on that screen then. Size of vertical screen is 1080x1920

**Comment by Makpptfox** [comment]
Being unable to resize is planned since it would cause UI clipping.

We will work on it.

**Comment by Makpptfox** [comment]
Added an option to unlock the resize locking in the version 1.0.2. (with a soft warning)
